Paperweight/urls.py
from django.contrib import admin
from django.urls import path, include

import documents.views as documents

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', documents.index),
    path('index/', documents.index),
    path('documents/', include('documents.urls')),
    path('registration/', include('registration.urls')),
]

documents/urls.py
from django.urls import path

import documents.views as documents

app_name = 'documents'
urlpatterns = [
    path(
        'dossiers/',
        documents.DossiersListView.as_view(),
        name='dossier_list'
    ),
    path(
        'dossiers/new',
        documents.DossierCreateView.as_view(),
        name='dossier_create'
    ),
    path(
        'dossiers/<int:pk>/edit',
        documents.DossierUpdateView.as_view(),
        name='dossier_update'
    ),
    path(
        'dossiers/<int:pk>/delete',
        documents.DossierDeleteView.as_view(),
        name='dossier_delete'
    ),
    path(
        'dossiers/<int:dossier_id>/sections/',
        documents.SectionsListView.as_view(),
        name='section_list'
    ),
    path(
        'dossiers/<int:dossier_id>/sections/new',
        documents.SectionsCreateView.as_view(),
        name='section_create'
    ),
    path(
        'dossiers/<int:dossier_id>/sections/<int:pk>/edit',
        documents.SectionsUpdateView.as_view(),
        name='section_update'
    ),
    path(
        'dossiers/<int:dossier_id>/sections/<int:pk>/delete',
        documents.SectionsDeleteView.as_view(),
        name='section_delete'
    ),
    path(
        'dossiers/<int:dossier_id>/sections/<int:section_id>',
        documents.DocumentListView.as_view(),
        name='document_list'
    ),
    path(
        'dossiers/<int:dossier_id>/sections/<int:section_id>/documents/<int:pk>',
        documents.DocumentDetailView.as_view(),
        name='document_detail'
    ),
    path(
        'dossiers/<int:dossier_id>/sections/<int:section_id>/documents/new',
        documents.DocumentCreateView.as_view(),
        name='document_create'
    ),
    path(
        'dossiers/<int:dossier_id>/sections/<int:section_id>/documents/<int:pk>/edit',
        documents.DocumentUpdateView.as_view(),
        name='document_update'
    ),
    path(
        'dossiers/<int:dossier_id>/sections/<int:section_id>/documents/<int:document_id>/download',
        documents.DocumentDownloadView.as_view(),
        name='document_download',
    ),
    path(
        'dossiers/<int:dossier_id>/sections/<int:section_id>/documents/<int:pk>/delete',
        documents.DocumentDeleteView.as_view(),
        name='document_delete'
    ),

    path('dossiers/search/', documents.DocumentSearchView.as_view(), name='search'),
    path('dossiers/<int:dossier_id>/sections_json', documents.sections_from_dossier_as_json),
    path('tags/', documents.documents_tags_list_as_json),
]

registration/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from registration.views import logout_view

app_name = 'registration'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

templates/base-with-navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link type="text/css" rel="stylesheet" href="{% static "css/base/base-with-navbar.css" %}"/>
    {% block stylesheets %}{% endblock %}
</head>
<body>
    <div class="main-container">
        {% include 'navbar.html' %}
        <div class="page-container">
            {% block body %}{% endblock %}
        </div>
    </div>

</body>
{% block scripts %}{% endblock %}
</html>

templates/index.html
{% extends 'base-with-navbar.html' %}
{% load static %}

{% block title %} Index {% endblock %}

{% block stylesheets %}
<link type="text/css" rel="stylesheet" href="{% static "css/index.css" %}"/>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="page-title">
            Index
        </div>
        <div class="page-description">
            <h2>Paperweight</h2>
            <p>
                Paperweight is a lightweight document database that helps in storing
                any kind of documents (invoices, instruction manuals, etc.) that are often placed in chunky dossiers
                that are a pain to search through.
            </p>
            <p>
                Paperweight lets users create digital dossiers that resemble the physical ones, only with a lot more flexibility.
                Sections can be created in each dossier to further improve the organization of documents.
            </p>

            <h2>Get Started</h2>
            {% if user.is_authenticated %}
                <p>
                    Cool! You're logged in! You can navigate with the navigation bar on the left to browse through
                    all dossiers or search a document.
                    To see or create dossiers, head to the <a href="{% url 'documents:dossier_list' %}">Dossiers</a> menu.
                </p>
            {% else %}
                <p>
                    It appears that you're not logged in. To do so, head to the <a href="{% url 'registration:login' %}?next=/index">Login Page</a>.
                    If you don't have an account, you have to ask the system administrator to create you one.
                </p>
            {% endif %}

            <h2>Author</h2>
            <p>
                Paperweight was created by <a href="https://www.linkedin.com/in/luis-tripa-954b9b1a8/" target="_blank">Luís Tripa</a>,
                a computer engineering student at Nova School of Science and Technology in Portugal.
            </p>
        </div>
    </div>
{% endblock %}

templates/navbar.html
{% load static %}
<div class="navbar-container">
    <a href="/index">
        <div class="navbar-title navbar-item">Paperweight</div>
    </a>

    <a href="/index">
        <div class="navbar-item">Main Page</div>
    </a>

    <a href="{% url 'documents:dossier_list' %}">
        <div class="navbar-item">Dossiers</div>
    </a>

    <a href="{% url 'documents:search' %}">
        <div class="navbar-item">Search</div>
    </a>

    {% if request.user.is_authenticated %}
        <a href="{% url 'registration:logout' %}">
            <div class="navbar-item">Logout</div>
        </a>
    {% else %}
        <a href="{% url 'registration:login' %}?next=/index">
            <div class="navbar-item">Login</div>
        </a>
    {% endif %}

</div>

templates/tag-form-input.html
{% load static %}

<div class="tag-container" id="document-tags-container">
    <!-- Tags -->
</div>
<div class="form-input">
    <label for="tag-input">Tags:</label>
    <input id="tag-input" autocomplete="off" placeholder="Search for a tag. Press space to add a new one"/>
    <div class="tag-container" id="tag-container">
        <!-- Tags -->
    </div>
</div>
{{ form.tags }}